### ISSUE TITLE
DEVELOPER STORY; Export Data to MySQL

### ISSUE THREAD

**Issue by JodieHillKitcherside** [JodieHillKitcherside/ci-project04-HKAirfieldDuxford#26]
As a **developer** I can **export booking details from each customer's confirmed booking** so that **I can store multiple bookings**

### **Acceptance Criteria:**
* Acceptance Criteria 1: Updated databases
* Acceptance Criteria 2: Created models for 'flight', 'aircraft' and 'booking'
* Acceptance Criteria 3: Automatically insert data in to MySQL

### **Tasks:**
- [ ] Task 1: Configure MySQL in settings.py
- [ ] Task 2: Define ERD models
- [ ] Task 3: Export data to MySQL
