### ISSUE TITLE
USER STORY; Booking Cart

### ISSUE THREAD

**Issue by JodieHillKitcherside** [JodieHillKitcherside/ci-project04-HKAirfieldDuxford#27]
As a **DA customer** I can **access my booking cart** so that **I can see what items I have selected before payment**

### **Acceptance Criteria:**
* Acceptance Criteria 1: User can add, update and delete items to cart
* Acceptance Criteria 2: Cart pops up on the top right of screen when user confirms a flight option 
* Acceptance Criteria 3: User can then have access to pay 

### **Tasks:**
- [ ] Task 1: Model the Cart and Cart Items, Views for Adding, Updating and Deleting Items 
- [ ] Task 2: Cart pop up
- [ ] Task 3: Cart management and CSS styling
