### ISSUE TITLE
DEVELOPER STORY; Automated Testing 

### ISSUE THREAD

**Issue by JodieHillKitcherside** [JodieHillKitcherside/ci-project04-HKAirfieldDuxford#28]
As a **developer** I can **automate tests throughout my project code** so that **I can confirm my system behaves as expected**

### **Acceptance Criteria:**
* Acceptance Criteria 1: Model, view and form tests all run true
* Acceptance Criteria 2: Cart tests run true
* Acceptance Criteria 3: No bugs or issues in testing environment or running tests

### **Tasks:**
- [ ] Task 1: Write model, view and form tests
- [ ] Task 2: Test cart functionality 
- [ ] Task 3: Run tests
