### ISSUE TITLE
USER STORY; Add, Update and Delete Options for User Profile

### ISSUE THREAD

**Issue by JodieHillKitcherside** [JodieHillKitcherside/ci-project04-HKAirfieldDuxford#29]
As a **DA customer** I can **add, update and delete my personal data in the user profile** so that **I can keep current and correct information for my profile**

### **Acceptance Criteria:**
* Acceptance Criteria 1: User can add, update and delete 
* Acceptance Criteria 2: User had profile update and delete confirmation 
* Acceptance Criteria 3: All tests run true 

### **Tasks:**
- [ ] Task 1: Create: profile form, update profile view, delete profile view
- [ ] Task 2: Create templates for Profile Update and Delete Confirmation
- [ ] Task 3: Test functionality
