### ISSUE TITLE
USER STORY; Flight options photos

### ISSUE THREAD

**Issue by JodieHillKitcherside** [JodieHillKitcherside/ci-project04-HKAirfieldDuxford#30]
As a **DA customer** I can **view photos of each flight options** so that **I can guide my choice for each flight options by seeing the aircraft or destinations**

### **Acceptance Criteria:**
* Acceptance Criteria 1: Each flight options has an image 
* Acceptance Criteria 2: Each image is styled appropriately 
* Acceptance Criteria 3: All models, admin, settings and urls updated

### **Tasks:**
- [ ] Task 1: Update models to store image files and modify admin panel
- [ ] Task 2: Update booking template to display images, update css for images
- [ ] Task 3: Configure settings and urls
