### ISSUE TITLE
USER STORY; Unauthorised Access

### ISSUE THREAD

**Issue by JodieHillKitcherside** [JodieHillKitcherside/ci-project04-HKAirfieldDuxford#31]
As a **DA customer** I can **clearly see forbidden pages** so that **rI am made aware I am not allowed to access data**

### **Acceptance Criteria:**
* Acceptance Criteria 1: Users cannot directly access data via urls if unauthorised
* Acceptance Criteria 2: The website data is secure
* Acceptance Criteria 3: Testing for this function is true 

### **Tasks:**
- [ ] Task 1: Check ownership or permissions in views
- [ ] Task 2: Customise a 403 forbidden page
- [ ] Task 3: Handle permission denied
